default:
    craft: []
    smelt: []
    use: []
    break: []
    interact: []
    entity: []
alchemist:
    craft: []
    smelt: []
    use: []
    break: []
    interact: []
    entity: []
cook:
    craft: []
    smelt: []
    use: []
    break: []
    interact: []
    entity: []
farmer:
    craft: []
    smelt: []
    use: []
    break: []
    interact: []
    entity: []
miner:
    craft: []
    smelt: []
    use: []
    break: []
    interact: []
    entity: []
smith:
    craft: []
    smelt: []
    use: []
    break: []
    interact: []
    entity: []
